# Use the official Python image from the Docker Hub
FROM python:3.11.10-bullseye

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./backend /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir uv
RUN uv sync


# Make port 800 available to the world outside this container
EXPOSE 8000

WORKDIR /app
# Run app.py when the container launches
ENTRYPOINT ["uv","run","uvicorn", "main:app", "--reload","--host","0.0.0.0","--port","8000"]